Feature/mx 1660 ldap search endpoint
robert-koch-institut/mex-common pull request #294
Opened 2024-09-24 11:36 UTC by vyvytranngoc

# PR Context

# Added

- extract ldap: get_persons methods and tests

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-09-24 12:09 UTC, cutoffthetop requested changes
looks good, just a few clean-up suggestions

2024-09-24 12:09 UTC, cutoffthetop commented on tests/ldap/test_extract.py
> +def test_get_persons_mocked(ldap_mocker: LDAPMocker) -> None:
```suggestion
def test_get_persons_by_name_mocked(ldap_mocker: LDAPMocker) -> None:
```

2024-09-24 12:09 UTC, cutoffthetop commented on tests/ldap/test_extract.py
> +def test_get_count_persons_mocked(ldap_mocker: LDAPMocker) -> None:
```suggestion
def test_get_count_of_found_persons_by_name_mocked(ldap_mocker: LDAPMocker) -> None:
```

2024-09-24 12:09 UTC, cutoffthetop commented on tests/ldap/test_extract.py
> +def test_get_person_mocked(ldap_mocker: LDAPMocker) -> None:
```suggestion
def test_get_person_by_id_mocked(ldap_mocker: LDAPMocker) -> None:
```

best if the original name of the function you are testing is reflected in the test, so it's easier to find and to indentify

2024-09-24 12:09 UTC, cutoffthetop commented on mex/common/ldap/extract.py
> +    employeeID: str = "*",
```suggestion
    objectGUID: str = "*",  # noqa: N803
    employeeID: str = "*",  # noqa: N803
```

2024-09-24 12:09 UTC, cutoffthetop commented on mex/common/ldap/extract.py
> +
```suggestion
```

2024-10-01 07:11 UTC, vyvytranngoc commented
ruff-linter fails. Could not comprehend which files were re-formatted. Therefore, I re-run ruff linter in .\tests\ldap and .\mex\common\ldap. But there all checks passed.

2024-10-01 07:38 UTC, cutoffthetop commented
> ruff-linter fails. Could not comprehend which files were re-formatted. Therefore, I re-run ruff linter in .\tests\ldap and .\mex\common\ldap. But there all checks passed.

@vyvytranngoc you can run `pdm lint` to run all pre-commit checks and linters on all files -- this should give you the same errors / re-formatting as the pipeline

2024-10-01 14:22 UTC, cutoffthetop approved these changes

2024-10-01 14:22 UTC, merged